name: quiz_factory
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  get: ^3.8.0
  http: ^0.12.2
  shared_preferences: ^0.5.10
  flutter_launcher_icons: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/quiz-factory-logo.png"
  google_fonts: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/quiz-factory-inapp.png
    # - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg